### PR TITLE
Migrate options for 3rd-party info from customizer to AS options

### LINKED ISSUE #935: Add option to disable Performance Survey
It will be good if you'll add an option to disable or hide Performance Survey block
Аннотация 2020-08-03 211127

### PR DESCRIPTION
**Pull request by candela97**
Resolves #935.

It seems odd that the "Performance Survey" option is the only one not available on our Options page, plus disabling these options in the customizer only hides the corresponding element, the feature itself is still loaded and required data is still fetched in the background. IMO these options are better suited in our Options page, and the customizer should only deal with native stuff. This makes it so that these features can be fully disabled as expected, and removes redundant and potentially misleading options from the customizer.

Note: I didn't remove or set to remove related SyncedStorage keys because they haven't been updated in a while (oops) and it seems like our `SyncedStorage.remove()` can't remove nested keys? I think this can be done with a separate utility that removes all keys that can't be found on current pages.

### CODE REVIEW

**Comment by MxtOUT** [comment]
Doesn't seem appropriate to me to treat our added content not in the customizer.
Why don't we convert the survey data, SteamSpy and SteamChart features into callback features and trigger them when the user enables them in the customizer?

**Comment by candela97** [comment]
I'm actually thinking about deprecating the customizer. Simply put: it's a pain to maintain, and for hiding stuff you don't want to see, you can just use a content blocker, which are much more versatile and efficient.

**Comment by MxtOUT** [comment]
I still think the solution I proposed here is the best one.
It doesn't matter whether the content is added by us or by Steam.
Content blockers are not as convenient as a drop-down menu that lists all possible content boxes on the store page.

And yes, the list will keep growing, but even if the object has 100 entries it shouldn't matter much.
Detecting outdated entries proves difficult though as not all boxes appear on every page.

**Comment by candela97** [comment]
> Content blockers are not as convenient as a drop-down menu that lists all possible content boxes on the store page.

I suppose so, but content blockers are so much more accessible now with element hider/picker/zapper features. I'm even willing to bet it's faster to hide something through the right click menu than finding the entry in our dropdown 😆

**Pull request closed without merging**
