### PR TITLE
FAchievementSort: fix parsing US date formats

### LINKED ISSUE #1908: [BUG] Achievement Sorting By Date Unlocked Does Nothing
### Expected Behavior

Achievements are ordered the date that they were unlocked according to the Ascending/Descending toggle when the Sort By drop down is set to `Date Unlocked`

### Actual Behavior

Achievements are ordered by the default order set by Steam

### Steps to Reproduce the Problem

  1. Log-in to steam
  2. Navigate to an achievement page (https://steamcommunity.com/id/<player identifier>/stats/<game id>/achievements/)
  3. Change Sort By drop down to `Date Unlocked`

### Specifications

  - Augmented Steam Version: 3.1.1
  - Browser Version: Firefox 124.0.2 (64-bit)

### PR DESCRIPTION
**Pull request by candela97**
Test the format before getting date formats if language is English. I'm starting to wonder if there're other unstable locales 😥. Fixes #1908.

### CODE REVIEW

**Comment by tfedor** [comment]
I wonder if we can just ignore languages completely, just make a large list of known date formats, and iterate that one, until we hit the format that can be parsed - you basically already do something like this, but in a more convoluted way.

It should simplify all these language shenanigans, since we see they're also not reliable.

**Comment by candela97** [comment]
Yeah regexes will be more flexible, but luxons format is straightforward and handy 😥. Or maybe just load the page in a locale that's stable and easy to parse? SteamDB uses finnish https://steamdb.info/blog/extension-achievements-update/

**Comment by tfedor** [comment]
Can't we just send string with a luxon format to luxon, and see if it throws or not? It should be throwing exception if it fails to parse, right?

If not, we can do what SteamDb does, we already have a solution to load the page in English, we could've been smarter and do some other language like they do 🤷

**Comment by candela97** [comment]
We can go with Czech I suppose 😂. But that means we'll need to remove English formats because it's unstable...

**Comment by tfedor** [comment]
That's fine with me, it would simplify it at least. Shame we need to do extra request though.

**Pull request merged**
