### PR TITLE
Add wishlist checkboxes

### LINKED ISSUE #844: Add wishlist checkboxes
Similar idea to DLC checkboxes -- let the user select multiple items, and add to cart all at once with a single click.

I have a working draft that looks like:

The add to cart element will appear if you have at least one item selected, and will show the number of items and total price.

TODO: 
1. Need some ideas on how to style the cart element.
2. The cart element in its current position overlaps our back-to-top button.
3. Select All/Filter to all selected? Tricky due to Steam detaching rows that are not visible, might need a script based on wishlist.js.

### PR DESCRIPTION
**Pull request by candela97**
Closes #844

### CODE REVIEW

**Comment by MxtOUT** [comment]
Oh, I didn't know that you could do this :)

**Comment by candela97** [comment]
Was this requested already? Feel free to ignore this if you're working on it, this still needs some work :P

**Comment by Revadike** [comment]
image
Cool

**Comment by MxtOUT** [comment]
Is this still being worked on? If so, could you please merge this with develop? It doesn't have the refactor changes applied yet

**Comment by candela97** [comment]
> Is this still being worked on? If so, could you please merge this with develop? It doesn't have the refactor changes applied yet

Yeah, I only moved the add to cart element to the center, so it no longer overlaps our back-to-top button. The rest is pretty much the same.

I think this still requires a few things:
1. Better layout for the add to cart element (looks pretty amateurish atm 😂)
2. Filter to selected items

**Comment by candela97** [comment]
> Is this still being worked on? If so, could you please merge this with develop? It doesn't have the refactor changes applied yet

Done. I've been using this for a while, though I still need help with the design (looks pretty amateurish atm 😂). Also it would be great if there's a way to filter to selected items.

**Comment by MxtOUT** [comment]
Confirmed working, but I'm not so satisfied with the position of the check boxes as you're moving away existing elements.

image

Spot 1: If you put the box here, it would be on the same line as the tags which could look nice
Spot 2: I think most people are positioning their mouse to the right of the wishlist rows, hence this might be a better position.

Also, an outline for selected items could make it easier to identify them when scrolling through the wishlist

**Comment by candela97** [comment]
> Spot 1: If you put the box here, it would be on the same line as the tags which could look nice
> Spot 2: I think most people are positioning their mouse to the right of the wishlist rows, hence this might be a better position.

The problem with these spots is that they'll behave differently in compact view: the tags column is hidden and spot 2 is where the "added on..." and remove link is displayed. Another idea is to add a sidebar that contains the checkbox (like hove_handle), but it seems a bit excessive.

> Also, an outline for selected items could make it easier to identify them when scrolling through the wishlist

👍 I didn't think of this. Though it'll be much better if we can show/filter to selected items.

**Comment by MxtOUT** [comment]
Hm, what if we do it [like this](https://github.com/tfedor/AugmentedSteam/issues/689#issuecomment-623532528) (just enable/disable redirection to cart)?
This would prevent the pollution of the already densely packed wishlist row

**Comment by MxtOUT** [comment]
I now realize that #1027 is actually a PR for that...
If we have that other feature, I don't think this also needs to be implemented.
What do you think?

**Comment by candela97** [comment]
To be honest, I think this feature here is a more solid enhancement, and I'd much prefer to work on this instead. #1027 I feel is more like an overly complicated workaround that, at the end of the day, only saves hitting the "Back" button when redirected to the Cart page.

> This would prevent the pollution of the already densely packed wishlist row

I honestly think the addition of a checkbox isn't that intruding, and is the only way to make it obvious this feature exists. Maybe I've gotten used to it already 😆

**Comment by MxtOUT** [comment]
> I honestly think the addition of a checkbox isn't that intruding, and is the only way to make it obvious this feature exists. Maybe I've gotten used to it already laughing

It's right next to the "Add to Cart" button, which is probably the most important button in a row.

>  #1027 I feel is more like an overly complicated workaround that, at the end of the day, only saves hitting the "Back" button when redirected to the Cart page.

This does too, right?

You could follow [this approach](https://github.com/IsThereAnyDeal/AugmentedSteam/pull/1027#issuecomment-960689554), so when you click "Add to Cart" it'd add it to the purchase total as it does now

**Comment by candela97** [comment]
Closing in favor of #1027.

**Pull request closed without merging**
