### PR TITLE
Refactor FHideTrademarks

### PR DESCRIPTION
**Pull request by candela97**
This is an experimental reimplementation of the hide trade marks feature. Instead of constantly having to update which selectors to check, just walk through all text nodes, while excluding specific tags and parent nodes.

I took some inspiration from the new uBlock Origin sciptlet that can replace text nodes. This filter can roughly achieve what's done here (only works on the dev version for now):
`store.steampowered.com##+js(rpnt, #text, /[\u00AE\u00A9\u2122]/, , stay, 1)`

The problems:
1. Are there more tags/ids to ignore/skip?
2. This feature is global, but we should exclude it on pages that don't have app titles, e.g. groups/friends
3. This registers a permanent MutationObserver to supports all kinds of popups and the new React stuff. The downside is it may affect performance and we'll need a global solution for other features too if this is the way to go.

### CODE REVIEW

**Comment by candela97** [comment]
Hmm, observing the body will likely cause issues with UGCs, I guess we need to maintain which nodes to observe afterall.

**Comment by tfedor** [comment]
What issues you think will it cause with UGCs?

**Comment by candela97** [comment]
UGCs like reviews/comments are dynamically loaded, which means we'll need to skip checking these nodes and we're back to constantly having to update the selectors.

**Comment by tfedor** [comment]
> UGCs like reviews/comments are dynamically loaded, which means we'll need to skip checking these nodes and we're back to constantly having to update the selectors.

I'm not sure I understand what the issue is to be honest, mutation observer will see dynamically loaded comments as well, wouldnt it?

**Comment by candela97** [comment]
Yes, but there a list of `id`s to skip to prevent the feature from being overzealous and removing symbols in strings that aren't game titles, and more have to be added to skip UGCs...

**Comment by tfedor** [comment]
We should probably finally deal with this. I don't feel strong either way, depends how confident you are with it. This one is kind of a pain to test.

**Comment by candela97** [comment]
Depends if it's ok if this feature is overzealous by default. But TBH I don't think this feature provides much value. I guess wanting to remove these symbols is just so it's easier to copy the title only?

**Comment by tfedor** [comment]
We had this in draft for a long time and it's also done before. I'm not sure if we need to work on this, so I'm going to close it, but if you do have interest in working on this further and you think it's worth it, feel free to reopen.

**Pull request closed without merging**
