### PR TITLE
Fix typo in French localization

### PR DESCRIPTION
**Pull request by LeMyst**
Replace SteamPeak by SteamPeek

### CODE REVIEW

**Comment by Blueberryy** [comment]
You should close that pull request because all translation updates is handled by POEditor.

**Comment by LeMyst** [comment]
> You should close that pull request because all translation updates is handled by POEditor.

What's the difference with #1416 #1417 and #1426 ?

**Comment by Blueberryy** [comment]
In these changes contributor changed base English translation plus he committed his changes on POEditor.
Other language translation changes should be done through POEditor

**Comment by LeMyst** [comment]
> POEditor

Ok, thanks for the information.

**Pull request closed without merging**
