### PR TITLE
fix: 🐛 #1548

### PR DESCRIPTION
**Pull request by pidanmeng**
custom 3rd-party sites enable custom protocal

### CODE REVIEW

**Comment by candela97** [comment]
I think the check can be performed in a single method like
```js
static format(link) {
    const protocolReg = /^[a-z]+:\/\//;
    const _link = protocolReg.test(link) ? link : `//${link}`;
    return this.escape(_link);
}
```
I also think a more descriptive name would be better, like `formatAndEscapeUrl` or simply `formatUrl`.

We also have custom profile links which should be fixed while at it:
https://github.com/IsThereAnyDeal/AugmentedSteam/blob/99811bf963b1334ff7560cecb2ff39696145a548/src/js/Content/Features/Community/ProfileHome/FCommunityProfileLinks.js#L71-L85

And there's a similar check here that can be replaced with the new method:
https://github.com/IsThereAnyDeal/AugmentedSteam/blob/99811bf963b1334ff7560cecb2ff39696145a548/src/js/Content/Features/Store/App/FSupportInfo.js#L45

**Comment by candela97** [comment]
Oh and don't forget the remove the `console.log`s when you're done testing 😄

**Comment by pidanmeng** [comment]
> I think the check can be performed in a single method like
> 
> ```js
> static format(link) {
>     const protocolReg = /^[a-z]+:\/\//;
>     const _link = protocolReg.test(link) ? link : `//${link}`;
>     return this.escape(_link);
> }
> ```
> 
> I also think a more descriptive name would be better, like `formatAndEscapeUrl` or simply `formatUrl`.
> 
> We also have custom profile links which should be fixed while at it:
> 
> https://github.com/IsThereAnyDeal/AugmentedSteam/blob/99811bf963b1334ff7560cecb2ff39696145a548/src/js/Content/Features/Community/ProfileHome/FCommunityProfileLinks.js#L71-L85
> 
> And there's a similar check here that can be replaced with the new method:
> 
> https://github.com/IsThereAnyDeal/AugmentedSteam/blob/99811bf963b1334ff7560cecb2ff39696145a548/src/js/Content/Features/Store/App/FSupportInfo.js#L45

get it

**Review by candela97 — APPROVED** [review]
Tested and works fine. Should probably update our default google links too, but that can be done later.

**Pull request merged**
