### PR TITLE
Added Safari Support

### PR DESCRIPTION
**Pull request by CandiceJoy**
Added support for Safari!  :)

The extension must be built on Mac.  You must have a TeamID to sign the extension (or use the XCode GUI to build the app).  I'm happy to sign and provide builds myself.

### CODE REVIEW

**Comment by CandiceJoy** [comment]
Made a small accident with regard to build targets.  Will resubmit.

**Comment by CandiceJoy** [comment]
I thought I made a mistake, but it turns out the time I thought I was wrong I was actually right; it works fine :)

**Comment by MxtOUT** [comment]
Hey, thanks for your effort!
Unfortunately we decided to not support Safari currently.

The fact that the extension has to be built on a Mac is one reason here.
I don't know if this could be solved by a containerization approach.

And obviously we can't accept your builds due to security reasons ):

**Comment by lothar-cell** [comment]
Can't it be done with virtualisation?

**Comment by MxtOUT** [comment]
I think our best bet would be to use docker containers, but yes, virtualization should also be possible

**Pull request closed without merging**
