### PR TITLE
Fix fetching badges when sorting by "A-Z"

### LINKED ISSUE #1710: [BUG] Badges page doesn't show all the badges with card drops remaining when sorted by alphabet.
### Steps to Reproduce the Problem

  1. Show «Badges With Card Drops Remaining».
  2. Ctrl + F, type «Play». (In my case 271 found.)
  3. Sort by alphabet.
  4. F3. (Now only 246 found.)

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Firefox 115.0.2 x64

### PR DESCRIPTION
**Pull request by candela97**
Fixes #1710

### CODE REVIEW

**Comment by candela97** [comment]
As a follow-up, I'm thinking about only loading our features when sorting by "In Progress". All of our added options (apart from grid view, which doesn't fetch additional pages) deal with badges that have drops remaining or are otherwise in progress, which get sorted to the top under "In Progress", and it's useless to fetch all of the remaining completed badges. This makes these features unusable for people with thousands of badges. Sorting by A-Z however mixes complete and incomplete badges, so we'll always need to fetch all pages.

**Review by MxtOUT — CHANGES_REQUESTED** [review]
Hm, it's weird that sorting options suddenly are not available when already sorting by "Rarity" or "Completed".
Of course the original problem stems from Steam selling filters as sort options (or hybrids of both).
The same reasoning applies to the "Calculate Drops" button.

**Comment by MxtOUT** [comment]
> As a follow-up, I'm thinking about only loading our features when sorting by "In Progress". All of our added options (apart from grid view, which doesn't fetch additional pages) deal with badges that have drops remaining or are otherwise in progress, which get sorted to the top under "In Progress", and it's useless to fetch all of the remaining completed badges. This makes these features unusable for people with thousands of badges. Sorting by A-Z however mixes complete and incomplete badges, so we'll always need to fetch all pages.

Again, I don't think that we should limit our sort options based on what's the currently selected "sort" option.
For people with thousands of badges we could implement the cancellation of the fetch requests.

**Comment by candela97** [comment]
> Hm, it's weird that sorting options suddenly are not available when already sorting by "Rarity" or "Completed". Of course the original problem stems from Steam selling filters as sort options (or hybrids of both). The same reasoning applies to the "Calculate Drops" button.

Problem is these 2 sorting methods will only display "completed" badges, so calculated drops, value, etc. will all be 0, and filtering to cards with drops remaing will also hide everything, which is more confusing IMO.

> For people with thousands of badges we could implement the cancellation of the fetch requests.

Yes, while sorting by "In Progress", since incomplete badges are sorted to the top, we can stop fetching more pages once we detect a completed badge. There're certainly people with thousands of badges, but I don't think there're many (besides bots) with thousands of incomplete badges lying around. But sorting by "A-Z" breaks this assumption. Incomplete badges can appear anywhere, and we'll be forced to fetch all pages, that's why I thought of only applying our features while sorting by "In Progress".

**Comment by candela97** [comment]
Oh ok, I thought most people will just sell the cards 😆

So only show additional filters and sorting options when sorting under "In Progress" and "A-Z", and always show a button to calculate drops and value? We can't use the `hasMultiplePages` prop to determine whether to auto-calculate because there might be no additional pages while sorting by the other 2 methods.

**Comment by MxtOUT** [comment]
> Oh ok, I thought most people will just sell the cards 😆

Before you sell them, you also need to acquire them, otherwise they'll still appear in your "Badges" section.

> So only show additional filters and sorting options when sorting under "In Progress" and "A-Z", and always show a button to calculate drops and value?

Almost, all "sorting" options should appear everywhere because it is just weird that some entries are not available depending on what "sort" you have currently selected.
For the filters and the button, yes, this is how I imagined it.

> We can't use the hasMultiplePages prop to determine whether to auto-calculate because there might be no additional pages while sorting by the other 2 methods.

That's fine, then auto-calculating doesn't take place when these sort options are selected.

**Pull request closed without merging**
