### PR TITLE
[WIP] Remove quotes from user notes display and add font color customization

### LINKED ISSUE #1227: [FEATURE REQUEST] Please remove the quotation marks from the Notes that we create on wishlisted items.
The are unnecessary and are actually distracting and annoying.  If I want quotation marks, I can type them myself like this "My Comment."  Just now, I copied the title of a game that included some quotation marks, so I ended up with four quotation marks on a single line because of the game title's quotation marks and the ones that AugmentedSteam automatically adds.  Then I created a new comment where I had a URL address and some /// marks to separate it from my actual omment, but the entire thing is wrapped in quotation marks so it's hard to distinguish my comment text apart from the URL because it is being grouped together with the marks.  I just don't see the point in having the quotation marks.  The default "Add a note" message doesn't have quotation marks around it, does it?!  And once you do add a note, the text becomes a different color, so it isn't that hard to distinguish it from other text.  Really, like I said, we can type quotation marks or any other marks if needed.  Let us do that ourselves.

### PR DESCRIPTION
**Pull request by candela97**
Closes #1227.

### CODE REVIEW

**Comment by MxtOUT** [comment]
I also prefer coloring notes with directives as proposed in the issue.
We'd need to inform the users about this though, maybe by having a placeholder in the input section that shows the usage of the directives?
Or a "?" button at the bottom left of the modal that gives instructions on how to color the text?

**Comment by candela97** [comment]
Oh ok. I was going to present both solutions, in case the directives proposal turned out to be overly complicated. I'll close this one then.

**Comment by idgas01** [comment]
I quit playing PC games a month ago.  But I'm still keeping an eye on this.  I still acquire free games from Epic Games and I still manually add those games to the Wishlist of one of my Steam accounts.  Are the "remove quotes" and "colored notes" still being worked on?  I noticed that there was an Augmented Steam update January 10 of this year.  Will these new features be available later this year?

**Comment by candela97** [comment]
Yeah it's being worked on. I'm a bit busy lately so it's gonna take a while before it's ready, but anyone can take up the task in the mean time!

**Pull request closed without merging**
