### PR TITLE
second attempt on making more stuff translateble

### PR DESCRIPTION
**Pull request by Blueberryy**
i hope it works

### CODE REVIEW

**Comment by candela97** [comment]
This ain't gonna work. You need to use `data-locale-html` attribute to insert strings with HTML tags. I create a PR of this and add you as a co-author.

**Comment by Blueberryy** [comment]
> This ain't gonna work. You need to use `data-locale-html` attribute to insert strings with HTML tags. I'll create a PR for this and add you as a co-author.

Oh okay, and is it possible to translate text that ***HTML.escape*** gets? Like hours and minutes here https://github.com/IsThereAnyDeal/AugmentedSteam/blob/68965f33a346a33fb1a405f87d8072727e4862e6/src/js/Content/Features/Store/App/FHowLongToBeat.js#L38

**Comment by candela97** [comment]
PR up #1530. Actually I was wrong about using `data-locale-html`, since HTML tags are not allowed in localization strings.

**Comment by candela97** [comment]
> Oh okay thanks, and is it possible to translate text that _**HTML.escape**_ gets? Like hours and minutes here
>
> https://github.com/IsThereAnyDeal/AugmentedSteam/blob/68965f33a346a33fb1a405f87d8072727e4862e6/src/js/Content/Features/Store/App/FHowLongToBeat.js#L38

Hmm, this data is fetched from 3rd party websites and stored as-is, so I'm not sure. I imagine it will cost ITAD more bandwidth if the data for every language supported by that site is stored.

**Comment by Blueberryy** [comment]
> > Oh okay thanks, and is it possible to translate text that _**HTML.escape**_ gets? Like hours and minutes here
> > https://github.com/IsThereAnyDeal/AugmentedSteam/blob/68965f33a346a33fb1a405f87d8072727e4862e6/src/js/Content/Features/Store/App/FHowLongToBeat.js#L38
> 
> Hmm, this data is fetched from 3rd party websites and stored as-is, so I'm not sure. I imagine it will cost ITAD more bandwidth if the data for every language supported by that site is stored.

Oh okay then another question is: Is it possible to make translations of [changelog.yml](https://github.com/IsThereAnyDeal/AugmentedSteam/blob/develop/changelog.yml) file?

**Comment by Blueberryy** [comment]
Probably too much questions for you [candela97](https://github.com/candela97) lol

**Comment by candela97** [comment]
No, not at all 😄

About the changelog, I'll ask about it, but some reasons I think it's not suitable for localizing:
1. We don't really have a formal process for it, so it's more of a "highlight" and may be missing details.
2. It may contain info related to extension management, future plans etc. so it's better if we have a single source to avoid miscommunication.
3. We only pull new translations on every update, so users won't get the localized text for the new version until the next.

**Comment by candela97** [comment]
> > Oh okay thanks, and is it possible to translate text that _**HTML.escape**_ gets? Like hours and minutes here
> > https://github.com/IsThereAnyDeal/AugmentedSteam/blob/68965f33a346a33fb1a405f87d8072727e4862e6/src/js/Content/Features/Store/App/FHowLongToBeat.js#L38
> 
> Hmm, this data is fetched from 3rd party websites and stored as-is, so I'm not sure. I imagine it will cost ITAD more bandwidth if the data for every language supported by that site is stored.

Looking at this again, language isn't the issue I think, instead it's having to parse the numbers and store them in separate fields (d,h,m). So instead of if a single field for each data type we'll need 2-3. I'll ask about this too.

**Pull request closed without merging**
