### PR TITLE
Update hosts for Steam assets

### PR DESCRIPTION
**Pull request by candela97**
Steam has been using these new hosts for a while now:
`steamcdn-a.akamaihd.net` -> `cdn.akamai.steamstatic.com`
`steamcommunity-a.akamaihd.net` -> `community.akamai.steamstatic.com`
`steamstore-a.akamaihd.net` -> `store.akamai.steamstatic.com`

Did I manage to catch all of them?
We might be better off storing some images (e.g. throbber.gif) locally, I'll do that later if needed...

### CODE REVIEW

**Comment by MxtOUT** [comment]
Hm, weird, for me it still uses the old domains (this is the front page)
image
Could be regional differences?

**Comment by candela97** [comment]
Are you sure it's not because you have AS enabled? 😆

**Comment by MxtOUT** [comment]
Yes, the steamstore-a.akamaihd.net comes from AS, but the new CDNs should still show up, right?
This is the front page without AS:
image
So I get Cloudflare and you get Akamai?

**Comment by candela97** [comment]
Yeah the old cdns still work, I guess to not break things, but everything should work on the new ones too.

I get Cloudflare too, but its probably a newer addition because ES has been using Akamai all over the place. We have a feature request to allow customising cdns (or simply follow what Steam picked for you), and there're most certainly others we haven't heard of, but nobody has complained so far... so I guess we should stick to one for now?

**Comment by MxtOUT** [comment]
Then I'd suggest using Cloudflare, as this is what's currently used by Steam

**Comment by candela97** [comment]
OK I used search and replace to change all akamai references, except in GameId.js, and update links in holidayprofile.js too.

**Pull request merged**
