### PR TITLE
Add link to download demo on wishlists

### PR DESCRIPTION
**Pull request by candela97**
Related to #447, perhaps a prerequisite?

This adds a link to download available demos on wishlists next to platform icons. Only visible in expanded view.

TODO
1. Different color? Now it's the same as the Early Access tag.
4. Params need to be split into chunks on larger wishlists, which means more requests. Not sure if Steam will be happy with us using this endpoint like this, so the result should be cached somehow.

### CODE REVIEW

**Comment by candela97** [comment]
Random thoughts:
1. The link could be placed in the title to support compact view, but that changes its position due to varying title lengths.
2. `api/appdetails` can be used to get demos too, but it does not support filtering to `demos` with multiple appids.
3. The ITAD server could compile and store a list of appids with their associated demos. The only problem I can think of is region/age restricted apps (the current endpoint will return nothing, and I assume the demo won't be downloadable anyway), but are pretty rare so probably doesn't matter (you'll have to have added the app prior to it being region/age restricted).
4. Regarding wishlist filtering, the only way to add custom filters as far as I can tell (and saw used in practice) is to redefine `g_Wishlist.BPassesFilters` with custom logic. That's a large script to inject (which we've been trying to avoid), and means we'll have to keep it up to date with Steam changes.

**Comment by candela97** [comment]
Latest commit implements a cache on fetched appids for 24 hours. This should be an ok feature even without the filtering functionality.

Still considering whether to put the button in the title, sucks to not support compact view...

**Comment by tfedor** [comment]
I'm trying to figure out how useful this feature actually is. If you have added it to your wishlist already, will you need to have a download demo button there? The decision whether you want it has already been made, no?

**Comment by candela97** [comment]
This has been requested a couple of times over the past few years, e.g. https://steamcommunity.com/discussions/forum/10/3094515496007356620/

People add unreleased games to their wishlist as well, and demos are often added at a later time. There're also time limited demos. In general this is just for convenience so you don't have to visit the store page everytime, and Steam provides a download demo button on sale pages too.

**Comment by tfedor** [comment]
I guess this is now completely outdated with the wishlist update, right?

**Comment by candela97** [comment]
Yes, `/IWishlistService/GetWishlistSortedFiltered/v1/` also returns demo appids now, so either Steam will implement this natively, or our approach can be simplified.

**Pull request closed without merging**
